Web component based - Svelte
Quebecca/qc_be_domain_color pull request #6
Opened 2024-12-18 15:02 UTC by atigiti

2024-12-19 14:17 UTC, marc-munos requested changes

2024-12-19 14:17 UTC, marc-munos commented on Resources/Private/WebComponents/DomainColorPickers/DomainColorPickers.svelte
> +        .svelte-s8w54d {
On n’ajoute jamais la classe css générée par svelte dans les styles. Il te suffit d’attacher la règle à l’élément (input ici).

2024-12-19 14:17 UTC, marc-munos commented on Resources/Private/WebComponents/DomainColorPickers/DomainColorPickers.svelte
> +        .input.svelte-s8w54d.svelte-s8w54d {
même remarque

2024-12-19 14:17 UTC, marc-munos commented on Resources/Private/WebComponents/DomainColorPickers/DomainColorPickers.svelte
> +        .svelte-s8w54d:focus-within {
même remarque

2024-12-19 14:17 UTC, marc-munos commented on Resources/Public/Css/DomainColorPicker.css
Pourquoi ce fichier ?

2024-12-19 14:17 UTC, marc-munos commented on Resources/Public/Scss/DomainColorPicker.scss
même question - vu que les styles sont à même le composant…

2024-12-19 14:17 UTC, marc-munos commented on gulpfile.js
même remarque, si les styles sont dans le composant, pas besoin d’un gulpfile

2024-12-23 12:28 UTC, atigiti commented
C'est corrigé.

2025-01-08 14:16 UTC, merged